version: '3.8'

services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    restart: unless-stopped
    ports:
      - "7888:80"
    environment:
      - PUID=501
      - PGID=501
    volumes:
      - ~/containers/heimdall:/config

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --label-enable

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9010:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/containers/portainer:/data

  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: unless-stopped
    networks:
      - guacnet

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    restart: unless-stopped
    ports:
      - "8190:8080"
    environment:
      - GUACD_HOSTNAME=guacd
      - MYSQL_HOSTNAME=192.168.3.2
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=guacamole_db
      - MYSQL_USER=guacuser
      - MYSQL_PASSWORD=guacpass
    networks:
      - guacnet

  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    restart: unless-stopped
    ports:
      - "8084:8083"
    environment:
      - PUID=501
      - PGID=501
    volumes:
      - ~/containers/calibre-web:/config
      - ~/Calibre Library:/books

  nextcloud:
    image: nextcloud:31
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - "8890:80"
    environment:
      - MYSQL_PASSWORD=qitlrtsx
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=192.168.3.2
    volumes:
      - ~/containers/nextcloud/html:/var/www/html
      - ~/containers/nextcloud/config:/var/www/html/config
      - ~/containers/nextcloud/data:/var/www/html/data

  code-server:
    image: linuxserver/code-server
    container_name: code-server
    restart: unless-stopped
    ports:
      - "8085:8443"
    environment:
      - PUID=501
      - PGID=501
      - TZ=Etc/UTC
      - PASSWORD=qitlrtsx
      - SUDO_PASSWORD=qitlrtsx
      - PROXY_DOMAIN=/code-server
    volumes:
      - ~/containers/code-server/config:/config
      - ~/workspace:/config/workspace

  drawio:
    image: jgraph/drawio
    container_name: drawio
    restart: unless-stopped
    ports:
      - "8087:8080"
    environment:
      - PUID=501
      - PGID=501

  mlflow-db:
    image: postgres:15
    container_name: mlflow-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=mlflow
      - POSTGRES_PASSWORD=mlflowpass
      - POSTGRES_DB=mlflow
    volumes:
      - ~/containers/mlflow/db:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"  # Web UI for managing buckets
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=qitlrtsx
    command: server /data --console-address ":9001"
    volumes:
      - ~/containers/minio/data:/data

  mlflow:
    image: burakince/mlflow:latest  # This image includes psycopg2
    container_name: mlflow
    restart: unless-stopped
    ports:
      - "5002:5002"
    depends_on:
      - mlflow-db
      - minio
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5002
      --backend-store-uri postgresql://mlflow:mlflowpass@mlflow-db:5432/mlflow
      --default-artifact-root s3://mlflow/
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=miniopassword
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000

  wp-db:
    image: mariadb:11
    container_name: wp-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=supersecretroot
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wpuser
      - MYSQL_PASSWORD=supersecretwp
    volumes:
      - ~/containers/wordpress/db:/var/lib/mysql

networks:
  guacnet:
    driver: bridge
