services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - DOCKER_USER=${USER}
      - PASSWORD=qitlrtsx
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      # Persist code-server config
      - "${HOME}/.config:/home/ajaraberrocal/.config"
      - "${HOME}/.local:/home/ajaraberrocal/.local"
      - "${HOME}:/home/ajaraberrocal"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped

